#!/usr/bin/env bash

set -e

# install docker
sudo dnf remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine

sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

if [ -f "/etc/docker/daemon.json" ]; then
  sudo mv /etc/docker/daemon.json /etc/docker/daemon.json.bak
else
  sudo mkdir -p /etc/docker/
  sudo tee /etc/docker/daemon.json <<EOF
{
  "data-root": "/mnt/raid/docker",
  "storage-driver": "overlay2",
  "selinux-enabled": true
}
EOF
fi

sudo usermod -aG docker "$USER"
sudo systemctl enable docker
sudo systemctl start docker