#!/usr/bin/env bash

set -euo pipefail

COMMAND=$1
ALIAS=${2:-$(basename "$(pwd)")}
if [[ -z "${COMMAND}" ]]; then
  echo "Please pass arguments to the script"
  exit 1
fi

CONFIG_DIR="$HOME/.config/goto"
CONFIG_FILE_NAME="config.yml"
CONFIG_FILE_PATH="${CONFIG_DIR}/${CONFIG_FILE_NAME}"

if [ ! -d "$CONFIG_DIR" ]; then
  mkdir -p "$CONFIG_DIR"
  echo "Creating directory $CONFIG_DIR"
fi

if [ ! -f "$CONFIG_FILE_PATH" ]; then
  touch "$CONFIG_FILE_PATH"
  echo "Creating file $CONFIG_FILE_PATH"
fi

case $COMMAND in

list)
  cat "$CONFIG_FILE_PATH"
  ;;

add)
  if grep -R "$ALIAS" "$CONFIG_FILE_PATH"; then
    echo ""
    echo "The alias already exists"
    exit 1
  fi
  echo "$ALIAS:$(pwd)" >>"$CONFIG_FILE_PATH"
  echo "Added alias $ALIAS:$(pwd) to list"
  ;;

remove)
  if grep -R "$ALIAS" "$CONFIG_FILE_PATH"; then
    sed -i "/\b\($ALIAS\)\b/d" "$CONFIG_FILE_PATH"
    echo "Removed alias $ALIAS:$(pwd)"
    exit 0
  fi
  cat "$CONFIG_FILE_PATH"
  echo ""
  echo "The alias specified does not exist"
  ;;

*)
  LINE=$(grep -R "$ALIAS" "$CONFIG_FILE_PATH")
  PATH=$(echo "$LINE" | cut -d':' -f2)
  if [[ -z "$PATH" ]]; then
    echo "The alias specified does not exist"
    exit 1
  fi
  cd "$PATH"
  ;;
esac
